# Generated by Django 4.1.2 on 2022-11-06 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publicacion',
            name='hilo',
        ),
        migrations.DeleteModel(
            name='Hilo',
        ),
        migrations.DeleteModel(
            name='Publicacion',
        ),
    ]
