# Generated by Django 4.1.2 on 2022-11-07 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_miembro_passwd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Miembro',
        ),
    ]
