# Generated by Django 4.1.3 on 2022-12-29 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_categoria_post_categoria'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
