# Generated by Django 4.1.3 on 2022-12-20 10:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo_nickname', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre del Equipo')),
                ('bio', models.CharField(max_length=500)),
                ('ciudad', models.CharField(max_length=50)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('instagram_url', models.CharField(blank=True, max_length=255, null=True)),
                ('twitter_url', models.CharField(blank=True, max_length=255, null=True)),
                ('website_url', models.CharField(blank=True, max_length=255, null=True)),
                ('fundador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_creados', to=settings.AUTH_USER_MODEL)),
                ('jugadores', models.ManyToManyField(related_name='equipos_unidos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=500)),
                ('direccion', models.CharField(max_length=500)),
                ('estado', models.CharField(max_length=500)),
                ('fecha_partido', models.DateField(verbose_name='Fecha del Partido')),
                ('equipos', models.ManyToManyField(blank=True, to='equipos.equipo')),
            ],
        ),
    ]
