# Generated by Django 4.1.3 on 2022-12-21 04:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_perfil_equipos'),
        ('equipos', '0003_remove_equipo_fundador_id_equipo_fundador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fundador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='equipos_creados', to='members.perfil'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(related_name='equipos_unidos', to='members.perfil'),
        ),
    ]
