# Generated by Django 4.1.3 on 2022-12-21 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_perfil_equipos'),
        ('equipos', '0004_alter_equipo_fundador_alter_equipo_jugadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fundador',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_creados', to='members.perfil'),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='jugadores',
            field=models.ManyToManyField(blank=True, related_name='usuarios', to='members.perfil'),
        ),
    ]
