# Generated by Django 4.1.3 on 2022-12-21 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_perfil_equipos'),
        ('equipos', '0005_alter_equipo_fundador_alter_equipo_jugadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipo',
            name='fundador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos_fundados', to='members.perfil'),
        ),
    ]
