# Generated by Django 4.1.3 on 2022-12-21 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipos', '0003_remove_equipo_fundador_id_equipo_fundador'),
        ('members', '0004_alter_perfil_foto_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='equipos',
            field=models.ManyToManyField(related_name='usuarios', to='equipos.equipo'),
        ),
    ]
