# Generated by Django 4.1.3 on 2022-12-30 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_perfil_equipos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='twitter_url',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='website_url',
        ),
        migrations.AddField(
            model_name='perfil',
            name='foto_de_portada',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
